IF-519: Setup minio and s3 database
IndustryFusion/IndustryFusion pull request #101
Opened 2021-11-24 12:52 UTC by jsylupp

2021-11-24 12:52 UTC, mattmikulina commented
Task linked: [IF-519 Object Storage](https://app.clickup.com/t/2177764/IF-519)

2021-11-30 14:27 UTC, florian-paul commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard.component.ts
> +    if (this.assetForm.get('imageKey')?.value !== ImageService.DEFAULT_ASSET_IMAGE_KEY) {
Restrict the deleteFunction for CreateMode

2021-11-30 14:30 UTC, florian-paul requested changes
Well done, just little changes :)

2021-11-30 14:30 UTC, florian-paul commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/storage/BaseClient.java
> +        return content.length > configuration.maxFileSizeMb * 1024 * 1024;
create variable for numbers

2021-11-30 14:30 UTC, florian-paul commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard.component.ts
> +    if (this.assetForm.get('imageKey')?.value !== ImageService.DEFAULT_ASSET_IMAGE_KEY) {
Restrict the deleteFunction for CreateMode

2021-11-30 15:05 UTC, merged