Import/Export integration
IndustryFusion/IndustryFusion pull request #105
Opened 2021-12-09 18:33 UTC by seemueller

2021-12-10 09:01 UTC, jsylupp requested changes
Your parts look good! Only three suggestions for your parts

2021-12-10 09:01 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/fleetmanager/FleetAssetRestService.java
> +    @GetMapping(path = "/companies/{companyId}/assetseries/{assetSeriesId}/assets/{assetId}/export")
seems to be unused

2021-12-10 09:01 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/ecosystemmanager/AssetTypeTemplateRestService.java
> +        OntModel model = assetTypeTemplateService.getAssetTypeTemplateRdf(assetTypeTemplateId);
Consider renaming Rdf everywhere to Owl for consistency

2021-12-10 09:01 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/ontology/BlankNodeProcessor.java
> +        if (id != null && id.startsWith("_:b") && node.size() == 1) {
maybe give string '_:b' a meaningfull variable name

2021-12-13 10:04 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/fleetmanager/FleetAssetRestService.java
> +    @GetMapping(path = "/companies/{companyId}/assetseries/{assetSeriesId}/assets/{assetId}/export")
removed

2021-12-13 10:09 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/ecosystemmanager/AssetTypeTemplateRestService.java
> +        OntModel model = assetTypeTemplateService.getAssetTypeTemplateRdf(assetTypeTemplateId);
While RDF is not exact the same as OWL and the export as consists partly on RDFS we should difference between OWL and RDF

2021-12-13 10:11 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/ontology/BlankNodeProcessor.java
> +        if (id != null && id.startsWith("_:b") && node.size() == 1) {
done

2021-12-13 12:38 UTC, merged