If 536 internationalization
IndustryFusion/IndustryFusion pull request #115
Opened 2021-12-29 08:36 UTC by florian-paul

2021-12-29 08:36 UTC, mattmikulina commented
Task linked: [IF-536 Internationalization implementieren](https://app.clickup.com/t/2177764/IF-536)

2022-01-07 11:22 UTC, jsylupp requested changes

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/core/store/threshold/threshold.model.ts
> +        // return 'Absolute lower & upper limit *';
remove comments in file

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/asset-type-list/asset-type-list.component.html
> +         class="list-container" currentPageReportTemplate="{first} to {last} of {totalRecords} Asset Types">
missing translation for currentPageReportTemplate?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/asset-type-dialog/asset-type-dialog.component.html
> +      <label class="if-label">{{ 'APP.COMMON.TERMS.NAME' | translate }} *</label>
Usage of * as prefix seems to be mixed over files. Here it is added in html (which might be the better choice) and e.g. for ABSOLUT_LOWER_AND_UPPER_LIMIT the * was added to the translation file.  Consider making it consistent to make it easier to follow for future developers.

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/asset-type-template/asset-type-template-wizard/asset-type-template-wizard-step-three/asset-type-template-wizard-step-three.component.html
> +                    placeholder="{{ 'APP.ECOSYSTEM.ASSET_TYPE_TEMPLATE.WIZARD.STEP_THREE.SELECT_ATTRIBUTE_PLACEHOLDER' | translate }}..." (onChange)="onChangeAttribute($event.value)">
as you have a specific entry for the placeholders, the three ... could probably be added to the translation files.

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/asset-type-template/asset-type-template-wizard/asset-type-template-wizard-step-one/asset-type-template-wizard-step-one.component.html
> +          <label class="if-label">{{ 'APP.ECOSYSTEM.ASSET_TYPE_TEMPLATE.WIZARD.STEP_ONE.SELECT_ASSET_TYPE_TEMPLATE' | translate }}</label>
translate placeholder

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-general-information/asset-series-wizard-general-information.component.html
> +            placeholder="{{ 'APP.FLEET.ASSET_SERIES_WIZARD.GENERAL_INFORMATION.SELECT_ASSET_TYPE_TEMPLATE' | translate }}..."
maybe add extra entry for placeholder to translation files to allow later changes of text (including the ...)

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/asset-type-template/asset-type-template-wizard/asset-type-template-wizard-step-one/asset-type-template-wizard-step-one.component.html
> +                      placeholder="{{ 'APP.ECOSYSTEM.ASSET_TYPE_TEMPLATE.WIZARD.STEP_ONE.SELECT_ASSET_TYPE' | translate }}..." (onChange)="onChangeAssetType($event.value)"
Consider adding placeholder entry for easier changes later (including the ...)

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/field-dialog/field-dialog.component.html
> +                  optionValue="id" placeholder="{{ 'APP.ECOSYSTEM.FIELD_DIALOG.SELECT_DATA_TYPE' | translate }}"></p-dropdown>
Consider adding placeholder entry for easier changes later

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/unit-dialog/unit-dialog.component.html
> +                    optionLabel="name" optionValue="id" placeholder="{{ 'APP.COMMON.TERMS.QUANTITY_TYPE' | translate }}"
Consider adding placeholder entry for easier changes later

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/factory-site-dialog/factory-site-dialog.component.html
> +          <p-dropdown [options]="factorySiteTypes" formControlName="type" placeholder="{{ 'APP.FACTORY.FACTORY_SITE_DIALOG.FACTORY_TYPE' | translate }}"
Consider adding placeholder entry for easier changes later

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/room-dialog/room-dialog.component.html
> +        <label class="if-label">{{  'APP.FACTORY.ROOM_DIALOG.SELECT_FACTORY_SITE' | translate }}</label>
Consider adding placeholder entry for easier changes later

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-attributes/asset-series-wizard-attributes.component.html
>              <div *ngIf="!fieldSource.get('fieldDataType')" class="p-col">DataType unknown!</div>
add translation

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard-shared/asset-wizard-shared-attributes/asset-wizard-shared-attributes.component.html
> +                        optionValue="id" placeholder="{{ 'APP.FLEET.ASSET_WIZARD.SHARED.ATTRIBUTES.SELECT_VALUE' | translate }}"></p-dropdown>
Consider adding placeholder entry for easier changes later

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-conditions/applet-conditions-value/applet-conditions-value.component.html
> +                  (onChange)="updateComponent($event.value)" placeholder="{{ 'APP.FUSION_APPLETS.EDITOR.CONDITIONS.CONDITIONS_VALUE.METRIC_LABEL' | translate }}'"
remove ' add end;  consider extra entry for placeholder

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/assets-list/assets-list.component.html
> +                              (showAssetCards)="onCardsViewClick()" itemTypeSingular="{{ 'APP.COMMON.TERMS.ASSET' | translate }}"
is [] around itemTypeSingular and -Plural missing?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/metrics-board/metrics-group/metrics-group.component.html
> +    translate.instant('APP.FACTORY.METRICS_BOARD.METRICS_GROUP.DEFAULT_LABEL') }}</label>
GENERAL_LABEL might be a more concise name

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-nameplate-and-connectivity-settings/asset-series-wizard-nameplate-and-connectivity-settings-tooltip/asset-series-wizard-nameplate-and-connectivity-settings-tooltip.component.html
> +    <label class="if-label">{{ 'APP.FLEET.ASSET_SERIES_WIZARD.NAMEPLATE_AND_CONNECTIVITY_SETTINGS.TOOLTIP.PLC4X_CUMMUNICATION' | translate }}:</label>
include : in translation?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-nameplate-and-connectivity-settings/asset-series-wizard-nameplate-and-connectivity-settings-tooltip/asset-series-wizard-nameplate-and-connectivity-settings-tooltip.component.html
>        <label class="protocol-label"> S7 (S7comm): </label>
add rest of file to translation?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-nameplate-and-connectivity-settings/asset-series-wizard-nameplate-and-connectivity-settings.component.html
> +                        placeholder="{{ 'APP.FLEET.ASSET_SERIES_WIZARD.NAMEPLATE_AND_CONNECTIVITY_SETTINGS.PROTECTION_CLASS_PLACEHOLDER' | translate }}...">
add ... to placeholder text

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard-shared/asset-wizard-shared-subsystems/asset-wizard-shared-subsystems.component.html
> +  <div *ngIf="!(subsystemFormArray?.controls?.length > 0) && isReview === true">{{ 'APP.FLEET.ASSET_WIZARD.SHARED.SUBSYSTEM.NO_SUBSYSTEMS_AVAILABLE' | translate }}no subsystems available</div>
remove text after translation, also in Line 21

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard-step/asset-wizard-step-metrics-thresholds/asset-wizard-step-metrics-thresholds.component.html
add translation in line 16

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/pages/asset-series-asset/asset-series-asset-digital-nameplate/asset-series-asset-digital-nameplate.component.html
> +      label="{{ 'APP.COMMON.TERMS.Street' | translate }}">{{(factorySite$ | async)?.line1}} {{(factorySite$ | async)?.line2}}</app-nameplate-item>
use Capital letters

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/content/gauge-chart/gauge-chart.component.ts
> +    // !!!
remove comment and add translations

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/content/notifications-list/notifications-list.component.html
> +                       [options]="[{name: this.transalte.instant('APP.SHARED.CONTENT.NOTIFICATIONS_LIST.OPEN_SINGULAR'), value: notificationStates.OPEN},
typo (and unnecessary this)

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/content/notifications-list/notifications-list.component.html
> +                                itemTypeSingular="{{ 'APP.SHARED.CONTENT.NOTIFICATIONS_LIST.NOTIFICATION' | translate }}"
[] missing?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/ui/table-filter/date-filter/date-filter.component.html
>        Date set</span>
missing translation

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/shared/shared.module.ts
> +// AoT requires an exported function for factories
what is AoT?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/app.component.ts
> +    // this language will be used as a fallback when a translation isn't found in the current language
is comment needed?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/app/app.component.ts
> +    // the lang to use, if the lang isn't available, it will use the current loader to get them
remove unused code

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/package.json
> +    "i18n:init": "ngx-translate-extract --input ./src --output ./src/assets/i18n/template.json --key-as-default-value --replace --format json",
maybe add comment what they are doing

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +				"FACTORY_SITE": "Fabrikseite",
Fabrikgelände, damit es einheitlich ist

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +					"CREATE": "Neue Fabrikseite erstellen",
Fabrikgelände, damit es einheitlich ist

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +				"CREATE": "erstellen.",
remove .

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +				"CREATE": "erstellen.",
Is empty space on purpose?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +            "MESSAGE": "Sind Sie sicher, dass Sie das Asset {{ itemToDelete }} löschen möchten ?"
remove space before ?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +					"DIALOG_DESCRIPTION": "Das Aktualisieren einer Asset-Typ-Vorlage erstellt\n   und speichert eine völlig neue Version der Vorlage"
is space on purpose?

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +						"CREATE_TEXT": "Ihre Asset-Typ-Vorlage wurde\n    erfolgreich erstellt",
same here

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +          "ABSOLUT_LOWER_AND_UPPER_LIMIT": "Absolute Unter- und Obergrenze *",
I would add the * to html

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/fr.json
> +          "ABSOLUT_LOWER_AND_UPPER_LIMIT": "Limites inférieures et supérieures absolues *",
I would add this to the html

2022-01-07 11:22 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/en.json
> +          "ABSOLUT_LOWER_AND_UPPER_LIMIT": "Absolute lower & upper limit *",
I would add this to the html

2022-01-07 15:38 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-footer/asset-series-wizard-footer.component.html
>              <ng-template #normalNext>Next</ng-template>
add translation

2022-01-07 15:38 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-wizard/asset-series-wizard-footer/asset-series-wizard-footer.component.html
>          <button type="button" class="if-button button-secondary" (click)="back.emit()">Back</button>
Add translation

2022-01-13 13:49 UTC, merged