Modelreposync
IndustryFusion/IndustryFusion pull request #121
Opened 2022-01-11 21:47 UTC by davidlane-iteratec

2022-01-13 09:17 UTC, jsylupp requested changes
Well done!

2022-01-13 09:17 UTC, jsylupp commented on fusionbackend/src/main/resources/config/application.yaml
> +  modelreposyncactive: true
kebab case for consistency and readability?

2022-01-13 09:17 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/AssetService.java
> +            assetDto.setSubsystemIds(null);
I think subsystemIds are needed here as this is the only reference to subsystems (there is no setSubsystems())

2022-01-13 09:17 UTC, jsylupp commented on fusionfrontend/src/app/core/services/api/if-api.service.ts
> +  getExportLinkEcosystemManager(exportType: string): string {
consider enum

2022-01-13 09:17 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/export/FleetManagerImportExportService.java
> +        int totalEntitySkippedCount = prevImportResult.getTotalEntitySkippedCount();
Shouldn't ProcessingResultDto also be used here?

2022-01-13 09:17 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/export/EcosystemManagerImportExportService.java
> +    private Path getEcomanFilePath(final String filename, final String extension) {
optional: consider full name EcosystemManager (same below and in line 241)

2022-01-13 09:33 UTC, davidlane-iteratec commented on fusionbackend/src/main/resources/config/application.yaml
> +  modelreposyncactive: true
ok

2022-01-13 10:23 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/ModelRepoSyncService.java
> +                final boolean isDirectoryEmpty = isDirectoryEmpty(localGitPath);
consider extracting methods

2022-01-17 12:19 UTC, davidlane-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/AssetService.java
> +            assetDto.setSubsystemIds(null);
Ok

2022-01-17 12:21 UTC, davidlane-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/export/FleetManagerImportExportService.java
> +        int totalEntitySkippedCount = prevImportResult.getTotalEntitySkippedCount();
I considered replaying ImportResult everywhere with ProcessingResultDto but rejected it in favour of a refactoring task. ImportResult is used also in Frontend.

2022-01-17 12:25 UTC, davidlane-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/export/EcosystemManagerImportExportService.java
> +    private Path getEcomanFilePath(final String filename, final String extension) {
Ok

2022-01-17 12:31 UTC, davidlane-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/ModelRepoSyncService.java
> +                final boolean isDirectoryEmpty = isDirectoryEmpty(localGitPath);
Ok

2022-01-17 12:47 UTC, davidlane-iteratec commented on fusionfrontend/src/app/core/services/api/if-api.service.ts
> +  getExportLinkEcosystemManager(exportType: string): string {
Ok

2022-01-17 17:27 UTC, merged