If 545 adjustments for internationalization
IndustryFusion/IndustryFusion pull request #127
Opened 2022-01-22 15:05 UTC by florian-paul

2022-01-22 15:05 UTC, mattmikulina commented
Task linked: [IF-545 Adjustments for internationalization](https://app.clickup.com/t/2177764/IF-545)

2022-01-24 08:01 UTC, jsylupp requested changes
Well done! Only little suggestions

2022-01-24 08:01 UTC, jsylupp commented on fusionfrontend/src/app/ecosystem/components/content/field-list/field-list.component.html
> +<p-confirmDialog #cd class="delete-confirm-dialog">
Consider extracting component

2022-01-24 08:01 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/ui/header/header.component.scss
> +  //vertical-align: -webkit-baseline-middle;
remove comment

2022-01-24 08:01 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +        "NO": "Nein",
alignment

2022-01-24 08:01 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/en.json
> +        "NO": "No",
alignment

2022-01-24 08:01 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/fr.json
> +        "NO": "Non",
alignment

2022-01-24 12:13 UTC, merged