If 526 group assets by enums
IndustryFusion/IndustryFusion pull request #128
Opened 2022-01-22 15:06 UTC by florian-paul

2022-01-22 15:06 UTC, mattmikulina commented
Task linked: [IF-526 Dashboard: Asset group by certain enums](https://app.clickup.com/t/2177764/IF-526)

2022-01-24 09:10 UTC, jsylupp requested changes

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/equipment-efficiency-list/equipment-efficiency-list.component.html
> +          <span class="p-text-bold p-ml-2" *ngIf="GroupByHelper.getFieldIndexOfSelectedEnum(asset, selectedEnum) == GroupByHelper.ASSET_FIELD_INDEX_WITHOUT_VALUE">{{ selectedEnum.optionLabel }} - Val
add translation

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/equipment-efficiency-list/equipment-efficiency-list.component.html
> +      <tr id="rowElement" style="cursor: pointer;">
preferably use class not style

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/equipment-efficiency-list/equipment-efficiency-list.component.html
> +          <span class="p-text-bold p-ml-2" *ngIf="GroupByHelper.getFieldIndexOfSelectedEnum(asset, selectedEnum) != GroupByHelper.ASSET_FIELD_INDEX_WITHOUT_VALUE">
(Just as idea: To hide information of the GroupByHelper you could also add a method like hasSelectedEnumValue)

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/equipment-efficiency-list/equipment-efficiency-list.component.scss
> +  height: 60px !important;
preferably 3rem

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/equipment-efficiency-list/equipment-efficiency-list.component.ts
> +  groupAssets(event: FieldOption) {
consider more concise name as event (same in Line 98 and 102)

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/equipment-efficiency-list/equipment-efficiency-list.component.ts
> +      this. rowGroupMetaDataMap = GroupByHelper.updateRowGroupMetaData(this.displayedFactoryAssets, this.selectedEnum);
remove space after this

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/maintenance-list/maintenance-list.component.html
> +          {{ selectedEnum.optionLabel }} - Value not found
translate

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/maintenance-list/maintenance-list.component.scss
> +  height: 60px !important;
preferably 3rem

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/maintenance-list/maintenance-list.component.ts
> +  setSearchText(event: string) {
consider more concise name than event (same below)

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/pages/equipment-efficiency-page/equipment-efficiency-page.component.ts
> +    this.fields$ = this.fieldsResolver.resolve();
Probably my bad. Not quite sure, but I assume that resolvers and queries should be separated (same line 77)  

this.fieldsResolver.resolve().subscribe();
this.fields$ = this.fieldsQuery.select...

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/pages/maintenance-page/maintenance-page.component.ts
> +    this.fields$ = this.fieldsResolver.resolve();
see comment on prev file

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/assets-list/assets-list.component.scss
> +  height: 60px !important;
3rem

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/assets-list/assets-list.component.ts
> +      this. rowGroupMetaDataMap = GroupByHelper.updateRowGroupMetaData(this.displayedFactoryAssets, this.selectedEnum);
remove space

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/assets-list-page/assets-list-page.component.ts
> +    this.fields$ = this.fieldsResolver.resolve();
see comment some pages before

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/factory-site-page/factory-site-page.component.ts
> +    this.fields$ = this.fieldsResolver.resolve();
same here. Maybe add to factoryResolver?

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/ui/table-searchbar/table-searchbar.component.ts
> +  // searchText: string;
remove comment

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/assets/i18n/de.json
> +        "TABLE_GROUP_BY": {
alignment (for all)

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/styles/components/_primeoverlaypanel.scss
> +.smallOverlayPanel  {
use hyphens (-) instead of camelCase, for all three

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/ui/table-group-by/table-group-by.component.scss
> +.groupBy-btn {
group-by-btn or groupby-btn

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/ui/table-group-by/table-group-by.component.scss
> +      font: normal normal normal 14px/1 FontAwesome;
use font size variable

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/shared/components/ui/table-group-by/table-group-by.component.ts
> +  emitSelectedEnum = new EventEmitter<FieldOption>();
(enumSelected would also be sufficient)

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/core/helpers/group-by-helper.ts
> +export class RowGroupData {
(RowGroupCount might be more concise)

2022-01-24 09:10 UTC, jsylupp commented on fusionfrontend/src/app/core/helpers/group-by-helper.ts
> +  size: number;
(size or count?)

2022-01-24 11:21 UTC, merged