IF-41: Instantiate asset
IndustryFusion/IndustryFusion pull request #19
Opened 2021-06-25 09:27 UTC by jsylupp

2021-06-25 09:27 UTC, mattmikulina commented
Task linked: [IF-41 Instantiate Asset (Fleet Manager)](https://app.clickup.com/t/2177764/IF-41)

2021-06-25 10:06 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetSeriesDetailsMapper.java
> +        int assetCount = Optional.of(entity).map(AssetSeries::getAssets).map(Set::size).orElse(0);
test comment

2021-06-25 10:17 UTC, florian-paul commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetSeriesDetailsMapper.java
> +                .assetCount((long) assetCount)
Test

2021-06-25 10:17 UTC, seemueller commented on fusionfrontend/src/app/ecosystem/components/content/asset-type-template/asset-type-template-wizard/asset-type-template-wizard-main/asset-type-template-wizard-main.component.html
> +<div class="if-wizard-wrapper">
test

2021-06-25 10:35 UTC, jsylupp commented on fusionfrontend/src/app/common/i-f-common.module.ts
> +import { InputTextModule } from 'primeng/inputtext';
test123

2021-06-25 12:09 UTC, florian-paul requested changes

2021-06-25 12:09 UTC, florian-paul commented on fusionfrontend/src/assets/sass/components/_primedropdown.scss
> +  .p-inputtext {
Wenn man über die dropdown hovert, erscheint eine border für das input Feld

2021-06-25 12:09 UTC, florian-paul commented on fusionfrontend/src/app/resolvers/asset.resolver.ts
> +    let companyId = this.companyQuery.getActiveId();
Sollte er sich die CompnayId nicht über die route in line 34 holen? Oder funktioniert das nicht?

2021-06-25 12:09 UTC, florian-paul commented on fusionfrontend/src/app/resolvers/asset-series.resolver.ts
> +    let companyId = this.companyQuery.getActiveId();
Sollte er sich die CompnayId nicht über die route in line 34 holen? Oder funktioniert das nicht?

2021-06-28 08:05 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard-step/asset-wizard-step.model.ts
> +export enum AssetWizardStep {
In den Store kommen nur gecachte Daten aus dem Backend. Ein Enum sollte dort meines Wissen nicht hinein. Da es ein technisches Modell ist, ist die Nähe zum Wizard hilfreich. Bleibt also hier.

2021-06-29 07:08 UTC, merged

2021-07-02 15:02 UTC, jsylupp reviewed
changes done