If 193 asset series specifics data
IndustryFusion/IndustryFusion pull request #22
Opened 2021-07-02 06:38 UTC by seemueller

Changes on hash method necessary to work with fieldsource sets without is's

2021-07-02 06:38 UTC, mattmikulina commented
Task linked: [IF-193 specifics of data availability](https://app.clickup.com/t/2177764/IF-193)

2021-07-05 06:53 UTC, jsylupp requested changes
Sieht gut aus!
Habe nur Kleinigkeiten angemerkt.

Melde dich einfach nochmal, wenn die Tests im Backend entsprechend korrigiert sind.

2021-07-05 06:53 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/AssetSeriesService.java
> +    @Transactional
is it mandatory to set @transactional above every create method with nested objects if it already in the class declaration?

2021-07-05 06:53 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-create/asset-series-create.component.ts
> +      case 2:
consider using enum for values here (see ATT-wizard)

2021-07-05 06:53 UTC, jsylupp commented on fusionfrontend/src/app/fleet/components/content/asset-series-create/view-mode.enum.ts
> +export enum ViewMode {
Just an refactoring idea: Maybe we could use the same enum for all Dialogs and Wizards (at least per module)

2021-07-05 08:22 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/AssetSeriesService.java
> +        assetSeries.setCompany(targetCompany);
Shouldn't we add the new assetSeries to the list in company (bidirectional)? 
targetCompany.getAssetsSeries().add(assetSeries);

2021-07-05 08:24 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/AssetSeriesService.java
> +        assetSeries.setAssetTypeTemplate(assetTypeTemplate);
Same with reference in AssetTypeTemplate

2021-07-08 14:07 UTC, jsylupp approved these changes

2021-07-08 15:24 UTC, merged