IF-284: Asset wizard thresholds and save asset
IndustryFusion/IndustryFusion pull request #23
Opened 2021-07-07 15:57 UTC by jsylupp

2021-07-07 15:57 UTC, mattmikulina commented
Task linked: [IF-284 Add Thresholds to metrics (page 3) and save asset](https://app.clickup.com/t/2177764/IF-284)

2021-07-08 09:21 UTC, seemueller requested changes

2021-07-08 09:21 UTC, seemueller commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard-step/asset-wizard-step-metrics-thresholds/asset-wizard-step-metrics-thresholds.component.ts
> +      return null;
may not use many returns in one method

2021-07-08 09:21 UTC, seemueller commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard.component.ts
> +  }*/
remove unused code

2021-07-08 09:21 UTC, seemueller commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard.component.ts
> +      console.log('asset to save:', this.asset);
remove log

2021-07-08 09:21 UTC, seemueller commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard.component.ts
> +    this.isLoading$ = this.assetSeriesQuery.selectLoading(); // TODO: is this correct?
open todo here?

2021-07-08 09:21 UTC, seemueller commented on fusionfrontend/src/assets/sass/components/_labels.scss
> +// TODO: good naming?
yes ;)

2021-07-08 09:21 UTC, seemueller commented on fusionfrontend/src/assets/sass/components/_primeaccordion.scss
> +@import 'base/typography';
missing licence comment?

2021-07-08 09:21 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/fleetmanager/FleetAssetRestService.java
> +    // TODO: this should probably not be allowed
open todo?

2021-07-08 09:21 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/fleetmanager/FleetAssetRestService.java
> +    // TODO: what values should be allowed to be changed
open todo?

2021-07-08 09:21 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/rest/fleetmanager/FleetAssetRestService.java
> +    // TODO: this should probably not be allowed
open todo?

2021-07-08 09:21 UTC, seemueller commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/FieldInstanceService.java
> +                                        final int criticalValuesCount) {
here ist maby a shortcut with the XOR operator possible

!((a != null) ^ (b != null))

2021-07-09 08:09 UTC, merged