IF: 295 asset customer data
IndustryFusion/IndustryFusion pull request #27
Opened 2021-07-19 07:25 UTC by jsylupp

2021-07-19 07:25 UTC, mattmikulina commented
Task linked: [IF-295 Customer data](https://app.clickup.com/t/2177764/IF-295)

2021-07-19 14:03 UTC, fkn-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetMapper.java
> +                       @Lazy RoomMapper roomMapper) {
Bringt das @Lazy tatsächlich etwas Messbares? Welches Problem wurde damit gelöst?

2021-07-19 15:19 UTC, fkn-iteratec requested changes

2021-07-19 15:19 UTC, fkn-iteratec commented on fusionbackend/src/main/resources/db/migration/V9__IF-295_add_country_entity.sql
> +        foreign key (country_id) references country (id);
Es fehlen die Stammdaten für die Country-Tabelle

2021-07-20 08:42 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetMapper.java
> +                       @Lazy RoomMapper roomMapper) {
Ohne @Lazy würde eine zyklische Abhängigkeit zwischen RoomMapper und AssetMapper bestehen, die das Backend nicht ausführen lässt. Dieses Problem wurde dadurch behoben.

2021-07-20 08:44 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetMapper.java
> +        } else if (dto.getRoomId() != null) {
Nein wird es nicht. Soll ich es hier einbauen?

2021-07-20 08:46 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/model/FactorySite.java
> +
existiert schon in der Mitte ;)

2021-07-20 08:52 UTC, fkn-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetMapper.java
> +        } else if (dto.getRoomId() != null) {
Zwei Möglichkeiten:

1. Eine validate()-Methode im DTO und das wird vorab vom REST-Controller aufgerufen. Dort wird nur beprüft, dass entweder roomid oder room gesetzt sind.
2. Im Mapper validieren, dass wenn beide gesetzt sind, die ID gleich ist.

Entscheidet sich ein bisschen danach wie das DTO auch benutzt wird. Ich gehe davon aus, dass nur ein Wert immer gesetzt ist. Es könnte aber auch einen schrägen Use-Case geben, z.B. move Room, wo alter und neuer Raum übermittelt werden. Prüf das noch vorab.

2021-07-20 09:34 UTC, merged