If 299 create new applet
IndustryFusion/IndustryFusion pull request #33
Opened 2021-08-04 06:55 UTC by seemueller

2021-08-04 06:55 UTC, mattmikulina commented
Task linked: [IF-299 Create new Applet](https://app.clickup.com/t/2177764/IF-299)

2021-08-05 07:48 UTC, jsylupp requested changes

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-conditions/applet-conditions.component.scss
> +    box-shadow: 0 3px 6px #00000029;
use variable

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-conditions/applet-conditions.component.ts
> +    this.dropdownOperatorOptions = this.getOperatorDropdownValue();
rename suggestion: consider using wording options also in the method

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-conditions/applet-conditions.component.ts
> +    if (!this.conditions.operator) {
consider extracting in method(s) due to faster understanding of purpose in name

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-conditions/applet-conditions-value/condition-time-selector/condition-time-selector.component.ts
> +  conditionTimeDropdownValue: SelectItem[];
maybe "...Options" to have consistent naming

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-conditions/applet-conditions-value/condition-time-selector/condition-time-selector.component.ts
> +  private getConditionTimeDropValue() {
maybe rename to ..Options?

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-action-list/applet-action/applet-action.component.scss
> +    background: #FFFFFF 0% 0% no-repeat padding-box;
use variable

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-action-list/applet-action/applet-action.component.scss
> +    background: #FFFFFF 0% 0% no-repeat padding-box;
use variable

2021-08-05 07:48 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applet-editor/applet-action-list/applet-action/applet-action.component.ts
> +  showActionTypePanel(type: RuleActionType): boolean {
Name könnte evtl verwirren, da bei show bisher meist etwas angezeigt wurde. Vlt is...Visible

2021-08-06 07:01 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applets-overview/fusion-applets-overview.component.ts
> +    return snapshot.url.map(sement => sement.path).includes(subroute);
do you mean segment?

2021-08-06 15:29 UTC, merged