IF-301: connectivity settings asset series
IndustryFusion/IndustryFusion pull request #35
Opened 2021-08-09 15:16 UTC by fkn-iteratec

2021-08-10 08:40 UTC, jsylupp requested changes
Review for backend only

2021-08-10 08:40 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/service/AssetSeriesService.java
>          targetAssetSeries.copyFrom(sourceAssetSeries);
should'nt we add the lines above here as well with connectivity settings?

2021-08-10 08:40 UTC, jsylupp commented on fusionbackend/src/main/resources/db/migration/V12__IF-301_Added_connectivity_settings.sql
> +    add constraint UK_su1a43xou98sno10yyaxdc2ce unique (connectivity_settings_id);
consider using a readable name

2021-08-10 08:40 UTC, jsylupp commented on fusionbackend/src/test/java/io/fusion/fusionbackend/test/persistence/PersistenceTests.java
> +    void persistAssestSeriesWithConnectivitySettings() {
typo AssetSeries

2021-08-10 08:40 UTC, jsylupp commented on fusionbackend/src/test/java/io/fusion/fusionbackend/test/persistence/PersistenceTests.java
> +    void persistAssestSeriesWithConnectivitySettings_detachBeforeSave() {
typo AssetSeries

2021-08-10 08:40 UTC, jsylupp commented on fusionbackend/src/test/java/io/fusion/fusionbackend/test/persistence/PersistenceTests.java
> +        assertNotNull(foundSeries);
should we assert the connectivity settings as well?

2021-08-12 06:48 UTC, seemueller requested changes

2021-08-12 06:48 UTC, seemueller commented on fusionfrontend/src/app/components/ui/tooltip/tooltip.component.ts
> +/*      const dialogElements = document.getElementsByClassName('p-dialog-mask');
remove unused code

2021-08-12 06:48 UTC, seemueller commented on fusionfrontend/src/app/fleet/components/content/asset-series-create/asset-series-create-attributes/asset-series-create-attributes.component.scss
> +/*.content {
remove unused code

2021-08-12 06:48 UTC, seemueller commented on fusionfrontend/src/app/fleet/components/content/asset-series-create/asset-series-create-general-information/asset-series-create-general-information.component.html
> +        <!--<div *ngIf="assetSeries"> // TODO tse: why was this ngIf in here? -->
to prevent errors the ngif wait with DOM loading while the assetseries is loaded

2021-08-12 12:38 UTC, jsylupp approved these changes

2021-08-12 13:01 UTC, merged

2021-08-12 22:35 UTC, mattmikulina commented
Task linked: [IF-301 Create Connection in Asset Series](https://app.clickup.com/t/2177764/IF-301)