If-361: Add connection string to asset wizard
IndustryFusion/IndustryFusion pull request #38
Opened 2021-08-12 15:11 UTC by jsylupp

2021-08-12 23:25 UTC, mattmikulina commented
Task linked: [IF-361 Connection String for Assets](https://app.clickup.com/t/2177764/IF-361)

2021-08-13 06:15 UTC, fkn-iteratec requested changes

2021-08-13 06:15 UTC, fkn-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetDetailsMapper.java
> +    private final BaseAssetMapper baseAssetMapper;
Find ich gut, dass der BaseAssetMapper benutzt wird. Ein AssetDetailsDto ist ja ein Subtyp von BaseAssetDto. Sollte man das dann nicht auch mit dem AssetMapper machen. AssetDto ist auch in der Hierarchie.

2021-08-13 06:15 UTC, fkn-iteratec commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetDetailsMapper.java
Mir sind noch "seltsame Dinge" bei den Mappern aufgefallen. Unabhängig von diesem Ticket. Melde dich mal zum besprechen...

2021-08-13 06:15 UTC, fkn-iteratec commented on fusionfrontend/src/app/fleet/components/content/asset-wizard/asset-wizard.component.ts
> +      }
Warum hier diese Prüfung? Alle anderen Felder werden nicht extra geprüft.

2021-08-13 07:48 UTC, jsylupp commented on fusionbackend/src/main/java/io/fusion/fusionbackend/dto/mappers/AssetDetailsMapper.java
>      protected AssetDetailsDto toDtoDeep(Asset entity) {
Nein ist nicht nötig, da die Methode in der Super-Klasse abstract ist

2021-08-13 08:44 UTC, merged