IF-302: Alert notifications
IndustryFusion/IndustryFusion pull request #39
Opened 2021-08-13 08:45 UTC by jsylupp

2021-08-13 08:45 UTC, mattmikulina commented
Task linked: [IF-302 Show and edit Notifications](https://app.clickup.com/t/2177764/IF-302)

2021-08-16 08:13 UTC, seemueller requested changes

2021-08-16 08:13 UTC, seemueller commented on fusionfrontend/src/app/notifications/content/notifications-sub-header/notifications-sub-header.component.spec.ts
> +import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
licence text ist missing

2021-08-16 08:13 UTC, seemueller commented on fusionfrontend/src/app/notifications/pages/notifications-page/notifications-page.component.scss
> +//  @import '../base/base-list/base-list.component.scss';
remove unused code

2021-08-16 08:13 UTC, seemueller commented on fusionfrontend/src/app/notifications/pages/notifications-page/notifications-page.component.spec.ts
> +import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
missing licence text

2021-08-17 12:08 UTC, jsylupp commented on fusionfrontend/src/app/notifications/content/notifications-list/notifications-list.component.html
> +      <button type="button" class="if-button button-primary button-modal" style="font-size: 13px; height: 30px; margin: 5px 0 0 0;"
Will be solved in other story anyway

2021-08-17 12:29 UTC, merged