If 373 asset details maintenance
IndustryFusion/IndustryFusion pull request #53
Opened 2021-09-13 06:49 UTC by g1glh0rn

2021-09-13 06:49 UTC, mattmikulina commented
Task linked: [IF-373 Maintenance of an asset (Asset view)](https://app.clickup.com/t/2177764/IF-373)

2021-09-14 07:39 UTC, jsylupp requested changes

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/components/content/maintenance-progressbar/maintenance-progressbar.component.scss
>  }
add color-variables everywhere

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/maintenance-list/maintenance-list.component.ts
> +      return null;
return false?

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/dashboards/components/content/maintenance-list/maintenance-list.component.ts
> +      const map = this.displayedFactoryAssets.map(asset => asset.subsystemIds);
are there more specific names for map and reduce?

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-performance.component.html
>  <div class='asset-details-wrapper'>
correct class name for this component?

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-performance.component.scss
> +  .dater {
typo?

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/factory/services/factory-resolver.service.ts
>  // import { switchMap } from 'rxjs/operators';
remove

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/store/asset/asset.service.ts
> +  updateAssetWithFieldValue(asset: FactoryAssetDetailsWithFields, secondsInPast: number) {
add return type.  Maybe move to oispService?

2021-09-14 07:39 UTC, jsylupp commented on fusionfrontend/src/app/factory/services/factory-resolver.service.ts
> +              return this.assetService.updateAssetWithFieldValue(asset, 600);
just a question: Why 600?  Might this be changed later on?

2021-09-14 07:48 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-performance.component.scss
>      height: 170px;
consider using rem

2021-09-14 07:50 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-performance.component.html
> +      <div class="progress-bar-label">Operating Hours till Maintenance</div>
could be changed to <label>

2021-09-17 11:43 UTC, merged