IF-403: show applets tab in asset view
IndustryFusion/IndustryFusion pull request #57
Opened 2021-09-14 15:49 UTC by seemueller

2021-09-14 15:49 UTC, mattmikulina commented
Task linked: [IF-403 Show applets tab in Asset view](https://app.clickup.com/t/2177764/IF-403)

2021-09-16 10:07 UTC, jsylupp requested changes

2021-09-16 10:07 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applets-list/fusion-applets-list.component.html
> +    <div class="if-title">{{ filtedRules?.length | i18nPlural: titleMapping }}</div>
typo

2021-09-16 10:07 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applets-list/fusion-applets-list.component.scss
> +:host ::ng-deep .p-selectbutton .p-button.p-highlight {
consider creating global style-class

2021-09-16 10:07 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/components/fusion-applets-list/fusion-applets-list.component.ts
> +          const filterRule = this.filterRulesByStatus([rule])[0];
filteredRule?

2021-09-16 10:07 UTC, jsylupp commented on fusionfrontend/src/app/fusion-applets/pages/fusion-applets-overview/fusion-applets-overview.component.ts
> +
remove space

2021-09-17 06:38 UTC, seemueller commented on fusionfrontend/src/app/fusion-applets/components/fusion-applets-list/fusion-applets-list.component.scss
> +:host ::ng-deep .p-selectbutton .p-button.p-highlight {
it is too custom

2021-09-17 06:55 UTC, merged