If-422: performance view asset details
IndustryFusion/IndustryFusion pull request #63
Opened 2021-09-24 12:01 UTC by jsylupp

2021-09-24 12:01 UTC, mattmikulina commented
Task linked: [IF-422 Equipment Efficiency Dashboard in Asset Details](https://app.clickup.com/t/2177764/IF-422)

2021-09-27 09:33 UTC, seemueller requested changes

2021-09-27 09:33 UTC, seemueller commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-performance.component.scss
> +  color: #333333;
color variable missing

2021-09-27 09:33 UTC, seemueller commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-performance.component.scss
> +  color: #333333;
dito

2021-09-27 10:17 UTC, merged