If 425 transform assets table to primeng
IndustryFusion/IndustryFusion pull request #67
Opened 2021-09-28 13:46 UTC by florian-paul

2021-09-28 13:46 UTC, mattmikulina commented
Task linked: [IF-425 Transform table assets of FactoryOwner to primeNG table](https://app.clickup.com/t/2177764/IF-425)

2021-09-30 06:51 UTC, jsylupp commented on fusionfrontend/src/app/components/ui/table-filter/table-filter.component.ts
> +    this.tableFilters.every(filter => {
is every the wanted method here or forEach?

2021-09-30 06:55 UTC, jsylupp commented on fusionfrontend/src/assets/sass/components/_primetable.scss
> +  color: #95989a !important;
use variables

2021-09-30 06:56 UTC, jsylupp commented on fusionfrontend/src/assets/sass/components/_primetable.scss
> +    font-size: 16px;
use variable

2021-09-30 06:57 UTC, jsylupp commented on fusionfrontend/src/assets/sass/components/_primetable.scss
> +    font-size: 14px !important;
use variable for font-size and extract values of font-family to new variable and add it on all places

2021-09-30 06:58 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/factory-site-page/factory-site-page.component.ts
> +  selectTheAssets(selectedAssetIds: ID[]) {
(selectAssets would also be sufficient)

2021-09-30 07:08 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/assets-list/assets-list.component.ts
> +  searchAssets(event?): void {
maybe add type of event, also below

2021-09-30 07:13 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/assets-list/assets-list.component.html
> +      <p-button *ngIf="selectedFactoryAssets.length == 1" class="table-bar-button" (click)="setActiveRow(); showEditDialog();">
use ===, also below

2021-09-30 07:15 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/content/assets-list/assets-list.component.html
> +        <app-table-searchbar filterColumn="Asset" [itemsToBeFiltered]="this.factoryAssetDetailsWithFields"
maybe remove this

2021-09-30 07:16 UTC, jsylupp requested changes
Well done :) just some little suggestions for change

2021-09-30 09:29 UTC, merged