If-420: historical view asset details
IndustryFusion/IndustryFusion pull request #71
Opened 2021-10-04 15:16 UTC by jsylupp

2021-10-04 15:16 UTC, mattmikulina commented
Task linked: [IF-420 History View / Data Viewer](https://app.clickup.com/t/2177764/IF-420)

2021-10-05 09:25 UTC, florian-paul requested changes
well done, sieht echt cool aus :)

2021-10-05 09:25 UTC, florian-paul commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-historical-view/asset-historical-view.component.ts
> +        if (this.currentTimeslot === 'customDate') {
Das Warning funktioniert nicht, da currentTimeSlot undediend ist.

2021-10-05 09:25 UTC, florian-paul commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-historical-view/asset-historical-view.component.html
> +            <div class="clr-col-md-auto clr-align-self-start">
Kein Clarity

2021-10-05 09:25 UTC, florian-paul commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-historical-view/asset-historical-view.component.scss
> +      font-size: 12px;
Variable für font size

2021-10-05 12:05 UTC, jsylupp commented on fusionfrontend/src/app/components/content/notifications-list/notifications-list.component.html
> +      ></p-selectButton>
Ne eher ein nicht anpassen von bestehendem Code bzw. automatisch durch IDE. finde das andere auch schöner ;)

2021-10-05 12:15 UTC, jsylupp commented on fusionfrontend/src/app/factory/components/pages/asset-details/asset-performance/asset-historical-view/asset-historical-view.component.ts
> +    if (validateOptions) {
genau, so sehen Defaultwerte aus, die man am Ende der Argumente einer Funktion platzieren kann. Es wird einmal mit true und false aufgerufen. Davor war es mal optional im HTML. Danke für den Hinweis, hab das = false rausgenommen

2021-10-05 14:03 UTC, merged