If 484 sortability of maintenance due
IndustryFusion/IndustryFusion pull request #94
Opened 2021-11-03 11:07 UTC by florian-paul

2021-11-03 11:07 UTC, mattmikulina commented
Task linked: [IF-484 Maintenance Dashboard: Column "Days till Maintenance" + "Operating Hours till Maintenance" should be sortable](https://app.clickup.com/t/2177764/IF-484)

2021-11-04 08:48 UTC, g1glh0rn requested changes
working well in my test. provides quite some benefit to the maintenance dashboard.

2021-11-04 08:48 UTC, g1glh0rn commented on fusionfrontend/src/app/components/content/maintenance-progressbar/maintenance-progressbar.component.html
> +  </div>
are you sure, that 0 means "unknown"? Could also mean critical?

2021-11-04 08:48 UTC, g1glh0rn commented on fusionfrontend/src/app/store/factory-asset-details/factory-asset-details.model.ts
> +  operatingHoursTillMaintenance: number;
should we really include fields of an asset in the model? Not sure whether this is a good idea.

2021-11-05 09:23 UTC, merged